### ISSUE TITLE
The calculation of the FLOPs

### ISSUE THREAD

**Issue by peterzpy** [d-li14/involution#14]
This is an interesting work, but I wonder **why the FLOPs of RedNet are less than the ResNet** when using the same number of layers. It seems that comparing with ResNet, RedNet will additionally generate the involution weights, then slide through the feature map just like convolution operation.

**Comment by d-li14** [comment]
It is because the involution kernels are shared across channels and generated by 1x1 convolution (or say linear transformation). Anyway, you could practically calculate the FLOPs of our provided network architecture.
