### ISSUE TITLE
The code in Algorithm 1

### ISSUE THREAD

**Issue by zjuter0126** [d-li14/involution#18]
Hello,in your paper,the Algorithm I  you wrtie 
#################### forward pass ####################
x_unfolded = unfold(x) # B,CxKxK,HxW
x_unfolded = x_unfolded.view(B, G, C//G, K * K, H, W)

Howerver, in the PyTorh,the true shape of x_unfolded may be B,KxKxC,HxW
so as for me,the code maybe as followings:
x_unfolded = unfold(x) # B,KxKxC,HxW
x_unfolded = x_unfolded.view(B,  K * K, G, C//G,, H, W).permute(0,2,3,1,4,5)

**Comment by d-li14** [comment]
the second dimension of `unfold` output is indeed CxKxK, refer to https://pytorch.org/docs/master/generated/torch.nn.Unfold.html
