### ISSUE TITLE
损失为nan

### ISSUE THREAD

**Issue by Weiziwei521** [d-li14/involution#19]
您好，在cls任务上，当我用involution卷积替换resnet50的3*3卷积时，损失为nan，原因有可能是什么啊

**Comment by d-li14** [comment]
Do you use our code and config to train rednet50?

**Comment by Weiziwei521** [comment]
只借用了involution_naive.py文件，改小了学习率，现在开始正常训练了，谢谢您

**Comment by Weiziwei521** [comment]
但是训练结果，识别精度几乎为0，这有可能是什么原因呢

**Comment by whf9527** [comment]
> 但是训练结果，识别精度几乎为0，这有可能是什么原因呢

我的也是，请问你知道是什么问题造成的吗。感觉模型并没有被优化，参数没有跟新。
