### ISSUE TITLE
Why use 7x7 involution but not 3x3 involution?

### ISSUE THREAD

**Issue by MARD1NO** [d-li14/involution#2]
Congratulation! Nice work in rethink conv module!
A question is why you use 7x7 involution to instead the BottleNeck module's 3x3 convolution? Why not use 3x3 involution?
In my view, the modern CNN architecture randomly use large kernel like 5x5 or 7x7. And i just wondering the reason of large kernel involution.

**Comment by d-li14** [comment]
Thanks for your interest!
For vanilla convolution in modern CNNs, increasing kernel size from 3 to 5, 7 significantly increases parameters/FLOPs, which is not an efficient choice. In contrast, thanks to the elaborate design of involution, we could increase kernel size without much overhead, see Tab. 6a for ablation.
Overall, we find using both large and dynamic kernels plays a key role in the performance, especially detection and segmentation tasks, see our explanation in sections 5.1.2 and 5.1.3.

**Comment by MARD1NO** [comment]
> Thanks for your interest!
> For vanilla convolution in modern CNNs, increasing kernel size from 3 to 5, 7 significantly increases parameters/FLOPs, which is not an efficient choice. In contrast, thanks to the elaborate design of involution, we could increase kernel size without much overhead, see Tab. 6a for ablation.
> Overall, we find using both large and dynamic kernels plays a key role in the performance, especially detection and segmentation tasks, see our explanation in sections 5.1.2 and 5.1.3.

Thanks for your reply~
