### ISSUE TITLE
out_channel

### ISSUE THREAD

**Issue by cymdhx** [d-li14/involution#25]
你好，如果我想自己定义out_channel我应该怎么办呢

**Comment by d-li14** [comment]
The #output channel is equal to the #input channel. You could use an additional linear transform to change the channel number.

**Comment by cymdhx** [comment]
> The #output channel is equal to the #input channel. You could use an additional linear transform to change the channel number.
作者你好，不好意思打扰。我这样加对吗 
![image](https://user-images.githubusercontent.com/73769530/113837155-24180100-97c0-11eb-9071-7674cc0a53dc.png)

**Comment by cymdhx** [comment]
> The #output channel is equal to the #input channel. You could use an additional linear transform to change the channel number.

我是

> The #output channel is equal to the #input channel. You could use an additional linear transform to change the channel number.



> The #output channel is equal to the #input channel. You could use an additional linear transform to change the channel number.


大佬，我这样加对吗。
![Uploading image.png…]()

**Comment by cymdhx** [comment]
> > The #output channel is equal to the #input channel. You could use an additional linear transform to change the channel number.
> 
> 我是
> 
> > The #output channel is equal to the #input channel. You could use an additional linear transform to change the channel number.
> 
> > The #output channel is equal to the #input channel. You could use an additional linear transform to change the channel number.
> 
> 大佬，我这样加对吗。
> ![image](https://user-images.githubusercontent.com/73769530/113856426-cc839080-97d3-11eb-9762-e36e5ec59a6f.png)

使用上面的方法后遇到这个bug
![image](https://user-images.githubusercontent.com/73769530/113869511-630b7e00-97e3-11eb-9cce-4342d05379ee.png)
