### ISSUE TITLE
involution_cuda.py # line 27

### ISSUE THREAD

**Issue by ChaoFan96** [d-li14/involution#29]
Hi, my bug occur at # line27 in involution_cuda.py,  `kernel_code = cupy.cuda.compile_with_cache(code)`, and seem to be a **cupy compile error**:
> cupy.cuda.compiler.CompileException: /tmp/tmp69btppfa/45f36f9abded28e374e19885d0b4818c_2.cubin.cu(6): error: identifier "None" is undefined
/tmp/tmp69btppfa/45f36f9abded28e374e19885d0b4818c_2.cubin.cu(6): error: identifier "None" is undefined
/tmp/tmp69btppfa/45f36f9abded28e374e19885d0b4818c_2.cubin.cu(6): error: identifier "None" is undefined
 /tmp/tmp69btppfa/45f36f9abded28e374e19885d0b4818c_2.cubin.cu(13): error: identifier "None" is undefined
 /tmp/tmp69btppfa/45f36f9abded28e374e19885d0b4818c_2.cubin.cu(13): error: identifier "None" is undefined
    
I have no idea to deal with this, would you offer me any help?
Pytorch Environment: torch1.6+cu9.2, cupy-cuda9.2

**Comment by miraodasilva** [comment]
This issue is caused by using mixed precision (16 bit tensors) in your implementation. I had exactly the same issue and it was fixed when I used 32 bit.

**Comment by ChaoFan96** [comment]
> 
> 
> This issue is caused by using mixed precision (16 bit tensors) in your implementation. I had exactly the same issue and it was fixed when I used 32 bit.

This works for me, thank you so much~
