### ISSUE TITLE
关于这篇工作的一点理解

### ISSUE THREAD

**Issue by MARD1NO** [d-li14/involution#3]
哈哈又是我，英语有点蹩脚，就直接拿中文了

我的理解是以前的标准卷积，其卷积核在空间域上是共享的（比如一个3x3卷积核直接滑窗滑过去），而在通道域上是互相独立的。

而你们的想法是用两个像bottleneck结构的1x1标准卷积生成一个卷积核权重，形状为（N, Groups, Kernelsize, Kernelsize, H, w）。然后对输入做一个分组，卷积

而因为之前的两次1x1卷积已经聚合了通道上的信息，所以这里没有对通道进行独立（我猜也是为了节省计算量？），而是每一组的特征图在通道上共享卷积核，但在H, W空间维度上分别独立有一个卷积核

下面是我画的一个示意图

![image](https://user-images.githubusercontent.com/42901638/110892075-4ee07800-832e-11eb-9904-0c4fb3ef0bf1.png)

如我理解有误，还望作者指证，十分感谢

**Comment by d-li14** [comment]
It's roughly the same as our illustration figure. The motivation and possibility of sharing kernels across channels arise from inter-channel redundancy, while the advantage is computation efficiency.

**Comment by MARD1NO** [comment]
> It's roughly the same as our illustration figure. The motivation and possibility of sharing kernels across channels arise from inter-channel redundancy, while the advantage is computation efficiency.

Thanks！！！
