### ISSUE TITLE
测试使用involution_native训练出来的模型，精度几乎为0

### ISSUE THREAD

**Issue by whf9527** [d-li14/involution#37]
tran loss一直在下降，val loss 从一开始就几乎保持不变。将输出的模型拿出来测试，精度也几乎为0.。有大哥知道是什么原因造成的吗？或者碰见相关问题。  我猜测模型参数可能没有被优化。

**Comment by MacalDan** [comment]
老哥 找到问题了没

**Comment by whf9527** [comment]
> 老哥 找到问题了没

我那个放弃了，感觉只是我代码的问题。

**Comment by Fateeeeee** [comment]
和我一样，val loss一直为nan

**Comment by zinhoo** [comment]
抄袭的

**Comment by RizhaoCai** [comment]
> 抄袭的

我也从知乎过来看的

**Comment by whf9527** [comment]
什么啊？能翻译翻译不发自我的华为手机-------- 原始邮件 --------发件人： "CAI, Rizhao" ***@***.***>日期： 2021年8月18日周三 下午2:01收件人： d-li14/involution ***@***.***>抄送： storyteller ***@***.***>, State change ***@***.***>主    题： Re: [d-li14/involution] 测试使用involution_native训练出来的模型，精度几乎为0 (#37)



抄袭的



我也从知乎过来看的
