### ISSUE TITLE
cuda

### ISSUE THREAD

**Issue by dingguodong-826** [d-li14/involution#8]
![image](https://user-images.githubusercontent.com/57715990/111565724-d159b380-87d6-11eb-9c0e-2e1b51b727c6.png)
Hello, thank you very much for your work. I would like to ask what is the difference between these two. Is it feasible to use naive version without configuring CUDA environment

**Comment by d-li14** [comment]
Both are OK. The CUDA version should be faster and more memory-efficient with CuPy as a prerequisite. The naive version could run with pure PyTorch.
